CREATE TABLE `UserProvider` (
	`id` text PRIMARY KEY NOT NULL,
	`userId` text NOT NULL,
	`order` integer DEFAULT 0 NOT NULL,
	`providerName` text NOT NULL,
	`providerType` text NOT NULL,
	`physicianName` text,
	`patientId` text,
	`insurance` text,
	`patientMemberId` text,
	`groupId` text,
	`planName` text,
	`phone` text,
	`fax` text,
	`providerEmail` text,
	`address` text,
	`membershipIdFront` text,
	`membershipIdBack` text,
	`historyPhysical` integer DEFAULT false NOT NULL,
	`diagnosticResults` integer DEFAULT false NOT NULL,
	`treatmentProcedure` integer DEFAULT false NOT NULL,
	`prescriptionMedication` integer DEFAULT false NOT NULL,
	`imagingRadiology` integer DEFAULT false NOT NULL,
	`dischargeSummaries` integer DEFAULT false NOT NULL,
	`specificRecords` integer DEFAULT false NOT NULL,
	`specificRecordsDesc` text,
	`dateRangeFrom` text,
	`dateRangeTo` text,
	`allAvailableDates` integer DEFAULT false NOT NULL,
	`purpose` text,
	`purposeOther` text,
	FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON UPDATE no action ON DELETE cascade
);
